services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: penzi_project
      POSTGRES_USER: penzi_user
      POSTGRES_PASSWORD: penzi123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - penzi-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://penzi_user:penzi123@db:5432/penzi_project
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - penzi-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - penzi-network
    restart: unless-stopped

networks:
  penzi-network:
    driver: bridge

volumes:
  postgres_data: